CREATE TABLE "domain_scan_config" (
                                      "id_domain_scan_config" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                      "zone_transfer" boolean,
                                      "dns_aggregators" boolean,
                                      "certificate_transparency" boolean,
                                      "subject_alternate_name" boolean,
                                      "search_engines" boolean,
                                      "dns_records" boolean,
                                      "http_headers" boolean,
                                      "modified_date" timestamp,
                                      "modified_by" varchar,
                                      "dictionary_config" int
);

CREATE TABLE "dictionary_config" (
                                     "id_dictionary_config" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                     "dictionary_file" varchar
);

CREATE TABLE "app_config" (
                              "id_app_config" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                              "virus_total_key" varchar,
                              "censys_api_id" varchar,
                              "censys_api_secret" varchar,
                              "shodan_api_secret" varchar
);

CREATE TABLE "scan" (
                        "id_scan" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        "name" varchar,
                        "scanned_domain" varchar,
                        "is_running" boolean,
                        "domain_scan_config_id" int,
                        "vuln_scan_config_id" int
);

CREATE TABLE "domain" (
                          "id_domain" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          "name" varchar,
                          "source" varchar,
                          "ip_address" varchar,
                          "parent_domain" varchar,
                          "run_scan_id" int
);

CREATE TABLE "vuln_scan_config" (
                                    "id_vuln_scan_config" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                    "scanned_ports" varchar,
                                    "unencrypted_communication" boolean,
                                    "weak_ssh_credentials" boolean,
                                    "security_headers" boolean,
                                    "ssl_issues" boolean
);

CREATE TABLE "run_scan" (
                            "id_run_scan" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                            "start_date" timestamp,
                            "finish_date" timestamp,
                            "scan_id" int
);

CREATE TABLE "open_port" (
                             "id_open_port" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                             "open_port" int,
                             "ip_address" varchar,
                             "service" varchar,
                             "run_vuln_scan_id" int
);

CREATE TABLE "security_issue" (
                                  "id_security_issue" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                  "name" varchar,
                                  "description" varchar,
                                  "asset" varchar,
                                  "severity" varchar,
                                  "open_port_id" int
);

CREATE TABLE "run_vuln_scan" (
                                 "id_run_vuln_scan" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                 "start_date" timestamp,
                                 "finish_date" timestamp,
                                 "run_scan_id" int
);

CREATE TABLE "user_data" (
                             "id_user_data" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                             "username" varchar,
                             "password" varchar,
                             "email" varchar,
                             "user_role" varchar,
                             "reset_token" varchar
);

ALTER TABLE "domain_scan_config" ADD FOREIGN KEY ("dictionary_config") REFERENCES "dictionary_config" ("id_dictionary_config");

ALTER TABLE "scan" ADD FOREIGN KEY ("domain_scan_config_id") REFERENCES "domain_scan_config" ("id_domain_scan_config");

ALTER TABLE "scan" ADD FOREIGN KEY ("vuln_scan_config_id") REFERENCES "vuln_scan_config" ("id_vuln_scan_config");

ALTER TABLE "domain" ADD FOREIGN KEY ("run_scan_id") REFERENCES "run_scan" ("id_run_scan");

ALTER TABLE "run_scan" ADD FOREIGN KEY ("scan_id") REFERENCES "scan" ("id_scan");

ALTER TABLE "open_port" ADD FOREIGN KEY ("run_vuln_scan_id") REFERENCES "run_vuln_scan" ("id_run_vuln_scan");

ALTER TABLE "security_issue" ADD FOREIGN KEY ("open_port_id") REFERENCES "open_port" ("id_open_port");

ALTER TABLE "run_vuln_scan" ADD FOREIGN KEY ("run_scan_id") REFERENCES "run_scan" ("id_run_scan");

INSERT INTO user_data VALUES(1, 'admin', '7a3f9a3f6c11e35c7a443a825112a1d0:9cff5ed4aa32ee25759805c9760539897ade7525765a934f1051c12527f480a3ec3dc58b54810b79a9d14a1e9fa16e9fa48f656fad276807656f2ad9b98e6dbd', 'admin@localhost', 0);